### ISSUE TITLE
Is Wiki data availble?

### ISSUE THREAD

**Issue by qiuhaolu** [elliotschu/crosslingual-el#1]
Will you provide the WIKI data and training scripts? Thanks.

**Comment by elliotschu** [comment]
Hello, the training scripts are already added to this repository.  The wiki data is too large to store in the repo, so please email me and I'll send you a link.

**Comment by qiuhaolu** [comment]
Thanks for the Wiki data. Can you also upload the config file "config.wiki.ini"? I only found "config.cached.ini" in this repo, which is for the LDC2019T02 dataset.

**Comment by elliotschu** [comment]
I just added it to the correct repository, I had pushed it to the wrong one earlier.
